# Site settings
author: Danielle Ellis 
title: Why I Decided To Study Software Engineering 
header-img: img/home-bg.png
email: thedanielleellis@gmail.com
copyright_name: Danielle Ellis 
description: > # this means to ignore newlines until "baseurl:"
  All Roads to Tech 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  thedanielleellis

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
